// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: practice/IMDB/gunk/v1/admin/all.proto

package adminpb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddGenre struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *AddGenre) Reset() {
	*x = AddGenre{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGenre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGenre) ProtoMessage() {}

func (x *AddGenre) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGenre.ProtoReflect.Descriptor instead.
func (*AddGenre) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{0}
}

func (x *AddGenre) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AddGenre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddGenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *AddGenreRequest) Reset() {
	*x = AddGenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGenreRequest) ProtoMessage() {}

func (x *AddGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGenreRequest.ProtoReflect.Descriptor instead.
func (*AddGenreRequest) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{1}
}

func (x *AddGenreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddGenreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddGenre *AddGenre `protobuf:"bytes,1,opt,name=AddGenre,proto3" json:"AddGenre,omitempty"`
}

func (x *AddGenreResponse) Reset() {
	*x = AddGenreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGenreResponse) ProtoMessage() {}

func (x *AddGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGenreResponse.ProtoReflect.Descriptor instead.
func (*AddGenreResponse) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{2}
}

func (x *AddGenreResponse) GetAddGenre() *AddGenre {
	if x != nil {
		return x.AddGenre
	}
	return nil
}

type EditGenre struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *EditGenre) Reset() {
	*x = EditGenre{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditGenre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditGenre) ProtoMessage() {}

func (x *EditGenre) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditGenre.ProtoReflect.Descriptor instead.
func (*EditGenre) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{3}
}

func (x *EditGenre) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *EditGenre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EditGenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *EditGenreRequest) Reset() {
	*x = EditGenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditGenreRequest) ProtoMessage() {}

func (x *EditGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditGenreRequest.ProtoReflect.Descriptor instead.
func (*EditGenreRequest) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{4}
}

func (x *EditGenreRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *EditGenreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EditGenreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EditGenre *EditGenre `protobuf:"bytes,1,opt,name=EditGenre,proto3" json:"EditGenre,omitempty"`
}

func (x *EditGenreResponse) Reset() {
	*x = EditGenreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditGenreResponse) ProtoMessage() {}

func (x *EditGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditGenreResponse.ProtoReflect.Descriptor instead.
func (*EditGenreResponse) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{5}
}

func (x *EditGenreResponse) GetEditGenre() *EditGenre {
	if x != nil {
		return x.EditGenre
	}
	return nil
}

type DeleteGenre struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *DeleteGenre) Reset() {
	*x = DeleteGenre{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGenre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenre) ProtoMessage() {}

func (x *DeleteGenre) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGenre.ProtoReflect.Descriptor instead.
func (*DeleteGenre) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGenre) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *DeleteGenre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteGenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteGenreRequest) Reset() {
	*x = DeleteGenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenreRequest) ProtoMessage() {}

func (x *DeleteGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGenreRequest.ProtoReflect.Descriptor instead.
func (*DeleteGenreRequest) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGenreRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteGenreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *DeleteGenreResponse) Reset() {
	*x = DeleteGenreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenreResponse) ProtoMessage() {}

func (x *DeleteGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGenreResponse.ProtoReflect.Descriptor instead.
func (*DeleteGenreResponse) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteGenreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddMovie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	StoryLine string  `protobuf:"bytes,3,opt,name=StoryLine,proto3" json:"StoryLine,omitempty"`
	Genres    []int32 `protobuf:"varint,4,rep,packed,name=Genres,proto3" json:"Genres,omitempty"`
}

func (x *AddMovie) Reset() {
	*x = AddMovie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovie) ProtoMessage() {}

func (x *AddMovie) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovie.ProtoReflect.Descriptor instead.
func (*AddMovie) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{9}
}

func (x *AddMovie) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AddMovie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMovie) GetStoryLine() string {
	if x != nil {
		return x.StoryLine
	}
	return ""
}

func (x *AddMovie) GetGenres() []int32 {
	if x != nil {
		return x.Genres
	}
	return nil
}

type AddMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	StoryLine string  `protobuf:"bytes,2,opt,name=StoryLine,proto3" json:"StoryLine,omitempty"`
	Genres    []int32 `protobuf:"varint,3,rep,packed,name=Genres,proto3" json:"Genres,omitempty"`
}

func (x *AddMovieRequest) Reset() {
	*x = AddMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieRequest) ProtoMessage() {}

func (x *AddMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieRequest.ProtoReflect.Descriptor instead.
func (*AddMovieRequest) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{10}
}

func (x *AddMovieRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMovieRequest) GetStoryLine() string {
	if x != nil {
		return x.StoryLine
	}
	return ""
}

func (x *AddMovieRequest) GetGenres() []int32 {
	if x != nil {
		return x.Genres
	}
	return nil
}

type AddMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddMovie *AddMovie `protobuf:"bytes,1,opt,name=AddMovie,proto3" json:"AddMovie,omitempty"`
}

func (x *AddMovieResponse) Reset() {
	*x = AddMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieResponse) ProtoMessage() {}

func (x *AddMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieResponse.ProtoReflect.Descriptor instead.
func (*AddMovieResponse) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{11}
}

func (x *AddMovieResponse) GetAddMovie() *AddMovie {
	if x != nil {
		return x.AddMovie
	}
	return nil
}

type EditMovie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *EditMovie) Reset() {
	*x = EditMovie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMovie) ProtoMessage() {}

func (x *EditMovie) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMovie.ProtoReflect.Descriptor instead.
func (*EditMovie) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{12}
}

func (x *EditMovie) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *EditMovie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EditMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *EditMovieRequest) Reset() {
	*x = EditMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMovieRequest) ProtoMessage() {}

func (x *EditMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMovieRequest.ProtoReflect.Descriptor instead.
func (*EditMovieRequest) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{13}
}

func (x *EditMovieRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EditMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EditMovie *EditMovie `protobuf:"bytes,1,opt,name=EditMovie,proto3" json:"EditMovie,omitempty"`
}

func (x *EditMovieResponse) Reset() {
	*x = EditMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMovieResponse) ProtoMessage() {}

func (x *EditMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMovieResponse.ProtoReflect.Descriptor instead.
func (*EditMovieResponse) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{14}
}

func (x *EditMovieResponse) GetEditMovie() *EditMovie {
	if x != nil {
		return x.EditMovie
	}
	return nil
}

type DeleteMovie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *DeleteMovie) Reset() {
	*x = DeleteMovie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovie) ProtoMessage() {}

func (x *DeleteMovie) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovie.ProtoReflect.Descriptor instead.
func (*DeleteMovie) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteMovie) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *DeleteMovie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *DeleteMovieRequest) Reset() {
	*x = DeleteMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieRequest) ProtoMessage() {}

func (x *DeleteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieRequest.ProtoReflect.Descriptor instead.
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteMovieRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeleteMovie *DeleteMovie `protobuf:"bytes,1,opt,name=DeleteMovie,proto3" json:"DeleteMovie,omitempty"`
}

func (x *DeleteMovieResponse) Reset() {
	*x = DeleteMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieResponse) ProtoMessage() {}

func (x *DeleteMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieResponse.ProtoReflect.Descriptor instead.
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteMovieResponse) GetDeleteMovie() *DeleteMovie {
	if x != nil {
		return x.DeleteMovie
	}
	return nil
}

var File_practice_IMDB_gunk_v1_admin_all_proto protoreflect.FileDescriptor

var file_practice_IMDB_gunk_v1_admin_all_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x65, 0x2f, 0x49, 0x4d, 0x44, 0x42, 0x2f,
	0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x6c,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62,
	0x22, 0x44, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x50, 0x00, 0x12, 0x18, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06,
	0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x33, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x47, 0x65, 0x6e,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30,
	0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x4b, 0x0a, 0x10, 0x41,
	0x64, 0x64, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2f, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00,
	0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x45, 0x0a, 0x09, 0x45, 0x64, 0x69, 0x74,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x18, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18,
	0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22,
	0x4c, 0x0a, 0x10, 0x45, 0x64, 0x69, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42,
	0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x18, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28,
	0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x4e, 0x0a,
	0x11, 0x45, 0x64, 0x69, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x45, 0x64, 0x69, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e,
	0x45, 0x64, 0x69, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28,
	0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x47, 0x0a,
	0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x50, 0x00, 0x12, 0x18, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06,
	0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x34, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x38, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06,
	0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x7f, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a,
	0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x18, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x50, 0x00, 0x12, 0x1d, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6e,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30,
	0x00, 0x50, 0x00, 0x12, 0x1a, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a,
	0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x6e, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x50, 0x00, 0x12, 0x1d, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6e,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30,
	0x00, 0x50, 0x00, 0x12, 0x1a, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a,
	0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x4b, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x41,
	0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00,
	0x10, 0x00, 0x18, 0x00, 0x22, 0x45, 0x0a, 0x09, 0x45, 0x64, 0x69, 0x74, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08,
	0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x18, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30,
	0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x34, 0x0a, 0x10, 0x45,
	0x64, 0x69, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08,
	0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18,
	0x00, 0x22, 0x4e, 0x0a, 0x11, 0x45, 0x64, 0x69, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x45, 0x64, 0x69, 0x74, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x70, 0x62, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x42, 0x0a, 0x08,
	0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18,
	0x00, 0x22, 0x47, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00,
	0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x18, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00,
	0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x36, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a,
	0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00,
	0x18, 0x00, 0x22, 0x54, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00,
	0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x32, 0xf9, 0x03, 0x0a, 0x0c, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x08, 0x41, 0x64, 0x64,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e,
	0x41, 0x64, 0x64, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x65, 0x6e,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90,
	0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x45, 0x64, 0x69, 0x74, 0x47, 0x65,
	0x6e, 0x72, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x45, 0x64,
	0x69, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x47, 0x65, 0x6e,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90,
	0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x54, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x4b, 0x0a, 0x08,
	0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88,
	0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x45, 0x64, 0x69,
	0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62,
	0x2e, 0x45, 0x64, 0x69, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x45, 0x64, 0x69, 0x74,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88,
	0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x54, 0x0a, 0x0b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x1a,
	0x03, 0x88, 0x02, 0x00, 0x42, 0x3e, 0x48, 0x01, 0x50, 0x00, 0x5a, 0x23, 0x70, 0x72, 0x61, 0x63,
	0x74, 0x69, 0x63, 0x65, 0x2f, 0x49, 0x4d, 0x44, 0x42, 0x2f, 0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x3b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x80,
	0x01, 0x00, 0x88, 0x01, 0x00, 0x90, 0x01, 0x00, 0xb8, 0x01, 0x00, 0xd8, 0x01, 0x00, 0xf8, 0x01,
	0x01, 0xd0, 0x02, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_practice_IMDB_gunk_v1_admin_all_proto_rawDescOnce sync.Once
	file_practice_IMDB_gunk_v1_admin_all_proto_rawDescData = file_practice_IMDB_gunk_v1_admin_all_proto_rawDesc
)

func file_practice_IMDB_gunk_v1_admin_all_proto_rawDescGZIP() []byte {
	file_practice_IMDB_gunk_v1_admin_all_proto_rawDescOnce.Do(func() {
		file_practice_IMDB_gunk_v1_admin_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_practice_IMDB_gunk_v1_admin_all_proto_rawDescData)
	})
	return file_practice_IMDB_gunk_v1_admin_all_proto_rawDescData
}

var (
	file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
	file_practice_IMDB_gunk_v1_admin_all_proto_goTypes  = []interface{}{
		(*AddGenre)(nil),            // 0: adminpb.AddGenre
		(*AddGenreRequest)(nil),     // 1: adminpb.AddGenreRequest
		(*AddGenreResponse)(nil),    // 2: adminpb.AddGenreResponse
		(*EditGenre)(nil),           // 3: adminpb.EditGenre
		(*EditGenreRequest)(nil),    // 4: adminpb.EditGenreRequest
		(*EditGenreResponse)(nil),   // 5: adminpb.EditGenreResponse
		(*DeleteGenre)(nil),         // 6: adminpb.DeleteGenre
		(*DeleteGenreRequest)(nil),  // 7: adminpb.DeleteGenreRequest
		(*DeleteGenreResponse)(nil), // 8: adminpb.DeleteGenreResponse
		(*AddMovie)(nil),            // 9: adminpb.AddMovie
		(*AddMovieRequest)(nil),     // 10: adminpb.AddMovieRequest
		(*AddMovieResponse)(nil),    // 11: adminpb.AddMovieResponse
		(*EditMovie)(nil),           // 12: adminpb.EditMovie
		(*EditMovieRequest)(nil),    // 13: adminpb.EditMovieRequest
		(*EditMovieResponse)(nil),   // 14: adminpb.EditMovieResponse
		(*DeleteMovie)(nil),         // 15: adminpb.DeleteMovie
		(*DeleteMovieRequest)(nil),  // 16: adminpb.DeleteMovieRequest
		(*DeleteMovieResponse)(nil), // 17: adminpb.DeleteMovieResponse
	}
)

var file_practice_IMDB_gunk_v1_admin_all_proto_depIdxs = []int32{
	0,  // 0: adminpb.AddGenreResponse.AddGenre:type_name -> adminpb.AddGenre
	3,  // 1: adminpb.EditGenreResponse.EditGenre:type_name -> adminpb.EditGenre
	9,  // 2: adminpb.AddMovieResponse.AddMovie:type_name -> adminpb.AddMovie
	12, // 3: adminpb.EditMovieResponse.EditMovie:type_name -> adminpb.EditMovie
	15, // 4: adminpb.DeleteMovieResponse.DeleteMovie:type_name -> adminpb.DeleteMovie
	1,  // 5: adminpb.adminService.AddGenre:input_type -> adminpb.AddGenreRequest
	4,  // 6: adminpb.adminService.EditGenre:input_type -> adminpb.EditGenreRequest
	7,  // 7: adminpb.adminService.DeleteGenre:input_type -> adminpb.DeleteGenreRequest
	10, // 8: adminpb.adminService.AddMovie:input_type -> adminpb.AddMovieRequest
	13, // 9: adminpb.adminService.EditMovie:input_type -> adminpb.EditMovieRequest
	16, // 10: adminpb.adminService.DeleteMovie:input_type -> adminpb.DeleteMovieRequest
	2,  // 11: adminpb.adminService.AddGenre:output_type -> adminpb.AddGenreResponse
	5,  // 12: adminpb.adminService.EditGenre:output_type -> adminpb.EditGenreResponse
	8,  // 13: adminpb.adminService.DeleteGenre:output_type -> adminpb.DeleteGenreResponse
	11, // 14: adminpb.adminService.AddMovie:output_type -> adminpb.AddMovieResponse
	14, // 15: adminpb.adminService.EditMovie:output_type -> adminpb.EditMovieResponse
	17, // 16: adminpb.adminService.DeleteMovie:output_type -> adminpb.DeleteMovieResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_practice_IMDB_gunk_v1_admin_all_proto_init() }
func file_practice_IMDB_gunk_v1_admin_all_proto_init() {
	if File_practice_IMDB_gunk_v1_admin_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGenre); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGenreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditGenre); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditGenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditGenreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGenre); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGenreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMovie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditMovie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMovie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_practice_IMDB_gunk_v1_admin_all_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_practice_IMDB_gunk_v1_admin_all_proto_goTypes,
		DependencyIndexes: file_practice_IMDB_gunk_v1_admin_all_proto_depIdxs,
		MessageInfos:      file_practice_IMDB_gunk_v1_admin_all_proto_msgTypes,
	}.Build()
	File_practice_IMDB_gunk_v1_admin_all_proto = out.File
	file_practice_IMDB_gunk_v1_admin_all_proto_rawDesc = nil
	file_practice_IMDB_gunk_v1_admin_all_proto_goTypes = nil
	file_practice_IMDB_gunk_v1_admin_all_proto_depIdxs = nil
}
